modLoader="javafml"
loaderVersion="[4,)"
license="AGPL-3.0-or-later"
[[mods]]
modId="magicalmap_gametest"
version="1.0.0"
displayName="Magical Map verification"
[[dependencies.magicalmap_gametest]]
modId="magicalmap"
type="required"
versionRange="[0.1.0,)"
ordering="AFTER"
side="BOTH"
